name: Build App

on:
  push:
    branches:
      - feature/build

env:
  NODE_VERSION: '16'
  IONIC_VERSION: 'latest'
  CORDOVA_VERSION: '11.0.0'

jobs:
  android-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        platform: [android]
        android_version: ['10.1.2']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Ionic and Cordova globally
        run: |
          npm install -g @ionic/cli@${{ env.IONIC_VERSION }}
          npm install -g cordova@${{ env.CORDOVA_VERSION }}

      - name: Install project dependencies
        run: npm install

      - name: Prepare project
        run: npm run prepare

      - name: Add Android platform
        run: ionic cordova platform add android@${{ matrix.android_version }}

      - name: Build Android
        run: ionic cordova build android

  ios-build:
    runs-on: macos-latest

    strategy:
      matrix:
        os: [macos-latest]
        platform: [ios]
        ios_version: ['6.2.0']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Ionic and Cordova globally
        run: |
          npm install -g @ionic/cli@${{ env.IONIC_VERSION }}
          npm install -g cordova@${{ env.CORDOVA_VERSION }}

      - name: Install project dependencies
        run: npm install

      - name: Prepare project
        run: npm run prepare

      - name: Add iOS platform
        run: ionic cordova platform add ios@${{ matrix.ios_version }}

      - name: Build iOS
        run: ionic cordova build ios
